// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNWL8M3JLS6W_RVXqgoXBSsRQTZC3cmck',
    appId: '1:352672704002:web:9f4d86e55dd6b70b8b691b',
    messagingSenderId: '352672704002',
    projectId: 'paper-checker-51708',
    authDomain: 'paper-checker-51708.firebaseapp.com',
    storageBucket: 'paper-checker-51708.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYzUS4_85dFCWBpxz-PbHo3ckco-xE2Jo',
    appId: '1:352672704002:android:570296fb065457b38b691b',
    messagingSenderId: '352672704002',
    projectId: 'paper-checker-51708',
    storageBucket: 'paper-checker-51708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlzcRM_ENWcz_xRDi4nm0DQSAkR5kzSko',
    appId: '1:352672704002:ios:675fb02a624467118b691b',
    messagingSenderId: '352672704002',
    projectId: 'paper-checker-51708',
    storageBucket: 'paper-checker-51708.appspot.com',
    iosClientId: '352672704002-0etvu547kv2j00fu6b54bl19lmk4utlp.apps.googleusercontent.com',
    iosBundleId: 'com.example.paperChecker',
  );
}
